name: 'PublishBetaVersion'
on:
  push:
    tags:
      - 'beta-v*' # Push events to matching beta-v*, i.e. beta-v1.0, beta-v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install --frozen-lockfile
      - run: npm run test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: 'beta'
